name: spark-performance
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - absl-py=0.6.1
  - astor=0.7.1
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - gast=0.2.1.post0
  - grpcio=1.16.0
  - libprotobuf=3.6.1
  - markdown=2.6.11
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - pandas=0.23.4
  - protobuf=3.6.1
  - py4j=0.10.8.1
  - pyspark=2.4.0
  - python-dateutil=2.7.5
  - pytz=2018.9
  - six=1.12.0
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - termcolor=1.1.0
  - tqdm=4.15.0
  - werkzeug=0.14.1
  - zlib=1.2.11
  - blas=1.0=mkl
  - intel-openmp=2019.1
  - mkl=2019.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pip=18.1
  - python=3.6.8
  - setuptools=40.6.3
  - sqlite=3.26.0
  - wheel=0.32.3
  - pip:
    - psutil==5.4.8
